<?php
/*
 * Copyright (c) 2014 Joachim Basmaison
*
* This program is free software; you can redistribute it and/or modify it
* under the terms of the GNU General Public License as published by
* the Free Software Foundation; either version 2 of the License,
* or (at your option) any later version. This program is distributed in the
* hope that it will be useful, but WITHOUT ANY WARRANTY; without even the
* implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
*
* See the GNU General Public License for more details.
*/

$title = 'TmpFileUpload';
$this->headTitle($title);
use TmpFileUpload\Helper\CommonHelper as Helper;
?>
<div>
<?php
// Init Form
$form = $this->form;
$form->setAttribute('class', 'form-horizontal');
$form->prepare();

// Configure Errors Helper
$errorsHelper  = $this->plugin('formelementerrors');
$errorsHelper
    ->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>');
?>
<?php  echo $this->form()->openTag($form); ?>
<fieldset>
    <legend><?php  echo ($this->legend) ?: 'Single File Upload' ?></legend>
    <?php
    $elem = $form->get('file-upload');
    $elem->setLabelAttributes(array('class' => 'control-label'));
    $errors = $elem->getMessages();
    $errorClass = (!empty($errors)) ? ' error' : '';
    ?>
    <div class="control-group<?php  echo $errorClass ?>">
        <?php  echo $this->formLabel($elem); ?>
        <div class="controls">
            <?php  echo $this->formFile($elem); ?>
            <?php  echo $errorsHelper($elem); ?>
            <?php  if (!empty($this->tempFiles)) { ?>
                <!--
                Note: You might not want to render the file input in this
                case either, depending on your use-case.
                -->
                <div class="help-block">
                    Uploaded: <ul>
                    <?php  foreach ($this->tempFiles as $tempFile) { ?>
                        <li><?php  echo $this->escapeHtml($tempFile['name']) ?></li>
                    <?php  } ?>
                    </ul>
                </div>
            <?php  } ?>
        </div>
    </div>

    <div class="control-group">
        <div class="controls">
            <button class="btn btn-primary">Submit</button>
        </div>
    </div>

</fieldset>
<?php  echo $this->form()->closeTag($form); ?>
<hr>
<p><h5>Max File Size:</h5>
<ul>
<li><?php echo Helper::formatBytes(Helper::getUploadMaxFilesize()); ?></li>
</ul>
<h5>Valid MIME</h5>
<ul>
<?php  foreach ($mimes as $mime) : ?>
    <li><?php  echo $this->escapeHtml($mime->value);?></li>
<?php  endforeach; ?>
</ul>
<h5>Features</h5>
<ul>
<li>File deleted after 5 minutes</li>
<li>Meta remove from image</li>
<li>Random key for access</li>
</ul>
</p>
</div>