<?php
/*
* Copyright (c) 2014 Joachim Basmaison
*
* This program is free software; you can redistribute it and/or modify it
* under the terms of the GNU General Public License as published by
* the Free Software Foundation; either version 2 of the License,
* or (at your option) any later version. This program is distributed in the
* hope that it will be useful, but WITHOUT ANY WARRANTY; without even the
* implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
*
* See the GNU General Public License for more details.
*/

use TmpFileUpload\Helper\CommonHelper as Helper;
?>
<div>
    <a href="<?php  echo $this->url('upload')?>">&laquo; Main</a>
</div>
<h2>Share</h2>
<?php
error_log('formData: ' . print_r($this->formData, true));
$pubkey = $this->formData['pubkey'];
$link = "/upload/serve/$pubkey";
$mime = $this->formData['mime'];
$is_image = Helper::startsWith($mime, 'image/') ? true : false;
$img = '';
if ($is_image) {
    $img = '<img style="width: 50px;" src="/upload/serve/' . $pubkey .'">';
}
?>
<a href="<?php echo $link; ?>"><?php echo $img; ?>&nbsp;<?php echo $link; ?></a>