<?php
/*
* Copyright (c) 2014 Joachim Basmaison
*
* This program is free software; you can redistribute it and/or modify it
* under the terms of the GNU General Public License as published by
* the Free Software Foundation; either version 2 of the License,
* or (at your option) any later version. This program is distributed in the
* hope that it will be useful, but WITHOUT ANY WARRANTY; without even the
* implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
*
* See the GNU General Public License for more details.
*/
?>
<div>
    <a href="<?php  echo $this->url('upload')?>">&laquo; Main</a>
</div>

<h2>Share</h2>
<?php
$pubkey = $this->formData['file-upload']['pubkey'];
$link = "/upload/serve/$pubkey";
?>
Share: <a href="<?php echo $link; ?>"><?php echo $link; ?></a>