<?php
/*
Copyright (c) 2014 Joachim Basmaison

This file is part of TmpFileUpload <https://github.com/showi/TmpFileUpload>

TmpFileUpload is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

See the GNU General Public License for more details.
*/

$title = 'TmpFileUpload';
$this->headTitle($title);
use TmpFileUpload\Helper\CommonHelper as Helper;
?>
<div>
<?php
// Init Form
$form = $this->form;
$form->setAttribute('class', 'form-horizontal');
$form->prepare();

// Configure Errors Helper
$errorsHelper  = $this->plugin('formelementerrors');
$errorsHelper
    ->setMessageOpenFormat('<div class="help-block">')
    ->setMessageSeparatorString('</div><div class="help-block">')
    ->setMessageCloseString('</div>');
?>
<?php  echo $this->form()->openTag($form); ?>
<?php #echo $this->formFileSessionProgress(); // Must come before the file input! ?>
<fieldset>
    <?php
    $elem = $form->get('file-upload');
    $elem->setLabelAttributes(array('class' => 'control-label'));
    $errors = $elem->getMessages();
    $errorClass = (!empty($errors)) ? ' error' : '';
    ?>
    <div class="control-group<?php  echo $errorClass ?>">
        <?php  echo $this->formLabel($elem); ?>
        <div class="controls">
            <?php  echo $this->formFile($elem); ?>
            <?php  echo $errorsHelper($elem); ?>
            <?php  if (!empty($this->tempFiles)) { ?>
                <!--
                Note: You might not want to render the file input in this
                case either, depending on your use-case.
                -->
                <div class="help-block">
                    Uploaded: <ul>
                    <?php  foreach ($this->tempFiles as $tempFile) { ?>
                        <li><?php  echo $this->escapeHtml($tempFile['name']) ?></li>
                    <?php  } ?>
                    </ul>
                </div>
            <?php  } ?>
        </div>
    </div>

    <div class="control-group">
        <div class="controls">
            <button class="btn btn-primary"><?php echo $this->translate('Submit')?></button>
        </div>
    </div>

</fieldset>
<?php  echo $this->form()->closeTag($form); ?>
<div id="progress" class="help-block">
    <div class="progress progress-info progress-striped">
        <div class="bar"></div>
    </div>
    <p></p>
</div>
<hr>
<p>
<h5>Max File Size:</h5>
    <ul>
    <li><?php echo Helper::formatBytes(Helper::getUploadMaxFilesize()); ?></li>
    </ul>
<h5>Valid MIME</h5>
    <ul>
    <?php  foreach ($mimes as $mime) : ?>
        <li><?php  echo $this->escapeHtml($mime->value);?></li>
    <?php  endforeach; ?>
    </ul>
<h5>Features</h5>
    <ul>
        <li>File deleted after <?php echo $file_expire_in; ?></li>
        <li>Image Meta removed using <a href="www.exiv2.org/">exiv2</a></li>
        <li>Random key for file access</li>
    </ul>
<h5>Source</h5>
    <ul>
        <li><a href="https://github.com/showi/TmpFileUpload">https://github.com/showi/TmpFileUpload</a></li>
    </ul>
</p>
</div>