<?php
/*
* Copyright (c) 2014 Joachim Basmaison
*
* This program is free software; you can redistribute it and/or modify it
* under the terms of the GNU General Public License as published by
* the Free Software Foundation; either version 2 of the License,
* or (at your option) any later version. This program is distributed in the
* hope that it will be useful, but WITHOUT ANY WARRANTY; without even the
* implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
*
* See the GNU General Public License for more details.
*/

$form->prepare(); // The correct enctype is set here ?>
<?php  echo $this->form()->openTag($form); ?>

    <div class="form-element">
        <?php  $fileElement = $form->get('file-upload'); ?>
        <?php  echo $this->formLabel($fileElement); ?>
        <?php  echo $this->formFile($fileElement); ?>
        <?php  echo $this->formElementErrors($fileElement); ?>
    </div>

    <button>Submit</button>

<?php  echo $this->form()->closeTag(); ?>